import { IsoType } from "all-iso-language-codes"

export type Region = {
    name: string
    isoType: IsoType
    languages: string[]
}

export const regions: Region[] = [
    {
        name: "Scandinavia",
        languages: [
            "ee",
            "se",
            "im",
            "lt",
            "sj",
            "je",
            "dk",
            "no",
            "is",
            "gg",
            "ax",
            "fi",
            "fo",
            "lv",
        ],
        isoType: "639-1",
    },
    {
        name: "Europe",
        languages: [
            "li",
            "fr",
            "nl",
            "lu",
            "ch",
            "at",
            "de",
            "be",
            "mc",
            "it",
            "gi",
            "ad",
            "es",
            "sm",
            "pt",
            "va",
            "ie",
        ],
        isoType: "639-1",
    },
    {
        name: "Balkans",
        languages: ["al", "hr", "mt", "ba", "me", "rs", "si", "mk"],
        isoType: "639-1",
    },
    {
        name: "Greece",
        languages: ["gr", "cy"],
        isoType: "639-1",
    },
    {
        name: "Eastern Europe",
        languages: [
            "bg",
            "sk",
            "ua",
            "hu",
            "by",
            "pl",
            "cz",
            "ro",
            "ru",
            "md",
            "az",
            "am",
            "ge",
            "uz",
            "tm",
            "tj",
            "kg",
            "kz",
        ],
        isoType: "639-1",
    },
    {
        name: "Middle East & North Africa",
        languages: [
            "sd",
            "ly",
            "eh",
            "ma",
            "dz",
            "eg",
            "t",
            "ps",
            "lb",
            "om",
            "tr",
            "il",
            "qa",
            "iq",
            "sy",
            "ye",
            "jo",
            "bh",
            "ae",
            "sa",
            "kw",
            "af",
            "ir",
        ],
        isoType: "639-1",
    },
    {
        name: "Africa",
        languages: [
            "zm",
            "gn",
            "io",
            "ml",
            "ug",
            "tf",
            "et",
            "za",
            "er",
            "cd",
            "td",
            "bf",
            "dj",
            "na",
            "lr",
            "cf",
            "sh",
            "ng",
            "so",
            "km",
            "ss",
            "cg",
            "zw",
            "ga",
            "gm",
            "sc",
            "bi",
            "mg",
            "ne",
            "yt",
            "gw",
            "mz",
            "mu",
            "gq",
            "sl",
            "st",
            "ao",
            "cv",
            "mw",
            "ci",
            "bj",
            "tg",
            "re",
            "tz",
            "sz",
            "mr",
            "cm",
            "gh",
            "rw",
            "sn",
            "ke",
            "ls",
            "bw",
        ],
        isoType: "639-1",
    },
    {
        name: "Indian Subcontinent",
        languages: ["lk", "pk", "np", "mv", "in", "bt", "bd"],
        isoType: "639-1",
    },
    {
        name: "Asia",
        languages: [
            "vn",
            "tl",
            "th",
            "tw",
            "sg",
            "ph",
            "mm",
            "mn",
            "my",
            "mo",
            "la",
            "kr",
            "kp",
            "jp",
            "id",
            "hk",
            "cn",
            "kh",
            "bn",
        ],
        isoType: "639-1",
    },
    {
        name: "South America",
        languages: [
            "vi",
            "vg",
            "ve",
            "uy",
            "tc",
            "tt",
            "sr",
            "gs",
            "sx",
            "vc",
            "mf",
            "lc",
            "kn",
            "bl",
            "pr",
            "pe",
            "py",
            "pa",
            "ni",
            "ms",
            "mx",
            "mq",
            "jm",
            "hn",
            "ht",
            "gy",
            "gt",
            "gp",
            "gd",
            "gf",
            "fk",
            "sv",
            "ec",
            "do",
            "dm",
            "cw",
            "cu",
            "cr",
            "co",
            "cl",
            "ky",
            "br",
            "bv",
            "bq",
            "bo",
            "bz",
            "bb",
            "bs",
            "aw",
            "ar",
            "ag",
            "ai",
        ],
        isoType: "639-1",
    },
    {
        name: "Oceania",
        languages: [
            "wf",
            "vu",
            "um",
            "tv",
            "to",
            "tk",
            "sb",
            "ws",
            "pn",
            "pg",
            "pw",
            "mp",
            "nf",
            "nu",
            "nz",
            "nc",
            "nr",
            "fm",
            "mh",
            "ki",
            "hm",
            "gu",
            "pf",
            "fj",
            "ck",
            "cc",
            "cx",
            "au",
            "as",
        ],
        isoType: "639-1",
    },
]
