import { IsoType } from "all-iso-language-codes"

export type Region = {
    name: string
    isoType: IsoType
    languages: string[]
    countries: string[]
}

export const regions : Region[] = [
    {
        name: "Scandinavia",
        languages: [
            "ee",
            "se",
            "im",
            "lt",
            "sj",
            "je",
            "dk",
            "no",
            "is",
            "gg",
            "ax",
            "fi",
            "fo",
            "lv",
        ],
        countries: ["DK", "EE", "FI", "NO", "SJ", "SE"],
        isoType: "639-1",
    },
    {
        name: "Europe",
        languages: [
            "li",
            "fr",
            "nl",
            "lu",
            "ch",
            "at",
            "de",
            "be",
            "mc",
            "it",
            "gi",
            "ad",
            "es",
            "sm",
            "pt",
            "va",
            "ie",
        ],
        countries: ["AD", "AT", "BE", "FO", "AX", "FR", "DE", "GI", "VA", "IS", "IE", "IT", "LI", "LU", "MT", "MC", "NL", "PT", "SM", "ES", "CH", "GG", "JE", "IM"],
        isoType: "639-1",
    },
    {
        name: "Balkans",
        languages: ["al", "hr", "mt", "ba", "me", "rs", "si", "mk"],
        countries: ["AL", "BA", "BG", "HR", "ME", "RO", "RS", "SI", "MK"],
        isoType: "639-1",
    },
    {
        name: "Greece",
        languages: ["el"],
        countries: ["GR", "CY"],
        isoType: "639-1",
    },
    {
        name: "Eastern Europe",
        languages: [
            "bg",
            "sk",
            "ua",
            "hu",
            "by",
            "pl",
            "cz",
            "ro",
            "ru",
            "md",
            "az",
            "am",
            "ge",
            "uz",
            "tm",
            "tj",
            "kg",
            "kz",
        ],
        countries: ["BY", "CZ", "GE", "HU", "KZ", "LV", "LT", "MD", "PL", "SK", "UA"],
        isoType: "639-1",
    },
    {
        name: "Middle East & North Africa",
        languages: [
            "sd",
            "ly",
            "eh",
            "ma",
            "dz",
            "eg",
            "t",
            "ps",
            "lb",
            "om",
            "tr",
            "il",
            "qa",
            "iq",
            "sy",
            "ye",
            "jo",
            "bh",
            "ae",
            "sa",
            "kw",
            "af",
            "ir",
        ],
        countries: ["DZ", "LY", "MA", "EH", "SD", "TN", "EG","PS", "IR", "IQ", "IL", "JO", "KW", "LB", "QA", "SA", "SY", "AE", "TR", "YE", "XE"],
        isoType: "639-1",
    },
    {
        name: "Africa",
        languages: [
            "zm",
            "gn",
            "io",
            "ml",
            "ug",
            "tf",
            "et",
            "za",
            "er",
            "cd",
            "td",
            "bf",
            "dj",
            "na",
            "lr",
            "cf",
            "sh",
            "ng",
            "so",
            "km",
            "ss",
            "cg",
            "zw",
            "ga",
            "gm",
            "sc",
            "bi",
            "mg",
            "ne",
            "yt",
            "gw",
            "mz",
            "mu",
            "gq",
            "sl",
            "st",
            "ao",
            "cv",
            "mw",
            "ci",
            "bj",
            "tg",
            "re",
            "tz",
            "sz",
            "mr",
            "cm",
            "gh",
            "rw",
            "sn",
            "ke",
            "ls",
            "bw",
        ],
        countries: ["AQ", "AO", "BW", "BV", "BI", "CM", "CV", "CF", "TD", "KM", "YT", "CG", "CD", "BJ", "GQ", "ET", "ER", "GS", "TF", "DJ", "GA", "GM", "GH", "GN", "HM", "CI", "KE", "LS", "LR", "MG", "MW", "ML", "MR", "MU", "MZ", "NA", "NE", "NG", "GW", "RE", "RW", "SH", "ST", "SN", "SC", "SL", "SO", "ZA", "ZW", "SS", "SZ", "TG", "UG", "TZ", "BF", "ZM"],
        isoType: "639-1",
    },
    {
        name: "Indian Subcontinent",
        languages: ["lk", "pk", "np", "mv", "in", "bt", "bd"],
        countries: ["IN", "PK", "BG"],
        isoType: "639-1",
    },
    {
        name: "Asia",
        languages: [
            "vn",
            "tl",
            "th",
            "tw",
            "sg",
            "ph",
            "mm",
            "mn",
            "my",
            "mo",
            "la",
            "kr",
            "kp",
            "jp",
            "id",
            "hk",
            "cn",
            "kh",
            "bn",
        ],
        countries: ["AF", "AZ", "BH", "BD", "AM", "BT", "IO", "BN", "MM", "KH", "LK", "CN", "TW", "CX", "CC", "GE", "HK", "ID", "IQ", "JP", "KZ", "KP", "KR", "KG", "LA", "MO", "MY", "MV", "MN", "NP", "PH", "TL", "SG", "VN", "TJ", "TH", "XD", "XS"],
        isoType: "639-1",
    },
    {
        name: "South America",
        languages: [
            "vi",
            "vg",
            "ve",
            "uy",
            "tc",
            "tt",
            "sr",
            "gs",
            "sx",
            "vc",
            "mf",
            "lc",
            "kn",
            "bl",
            "pr",
            "pe",
            "py",
            "pa",
            "ni",
            "ms",
            "mx",
            "mq",
            "jm",
            "hn",
            "ht",
            "gy",
            "gt",
            "gp",
            "gd",
            "gf",
            "fk",
            "sv",
            "ec",
            "do",
            "dm",
            "cw",
            "cu",
            "cr",
            "co",
            "cl",
            "ky",
            "br",
            "bv",
            "bq",
            "bo",
            "bz",
            "bb",
            "bs",
            "aw",
            "ar",
            "ag",
            "ai",
        ],
        countries: ["AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", "GY", "PY", "PE", "SR", "UY", "VE"],
        isoType: "639-1",
    },
    {
        name: "Oceania",
        languages: [
            "wf",
            "vu",
            "um",
            "tv",
            "to",
            "tk",
            "sb",
            "ws",
            "pn",
            "pg",
            "pw",
            "mp",
            "nf",
            "nu",
            "nz",
            "nc",
            "nr",
            "fm",
            "mh",
            "ki",
            "hm",
            "gu",
            "pf",
            "fj",
            "ck",
            "cc",
            "cx",
            "au",
            "as",
        ],
        countries: ["AS", "AU", "SB", "CK", "FJ", "PF", "KI", "GU", "NR", "NC", "VU", "NZ", "NU", "NF", "MP", "UM", "FM", "MH", "PW", "PG", "PN", "TK", "TO", "TV", "WF", "WS"],
        isoType: "639-1",
    },
]
