export type Action =
    | `audio:${string}`
    | `audio:auto:$${string}`
    | `audio:auto:broadcast:${string}`
    | `audio:auto:broadcast:current`
    | `audio:auto:broadcast:next`
    | `audio:auto:broadcast:prev`
    | `audio:auto:broadcast:release`
    | `audio:auto:broadcast:name:${string}`
    | `audio:auto:broadcast:triplet:${string}.${string}.${string}`
    | `audio:auto:plugin:${string}`
    | `audio:auto:resolve:${string}`
    | `audio:auto:resolve:user:${string}`
    | `audio:auto:resolve:request:interaction:${string}`
    | `audio:auto:resolve:request:interaction:${string}@${string}`
    | `url`
    | `audio:broadcast:${string}`
    | `audio:broadcast:current`
    | `audio:broadcast:next`
    | `audio:broadcast:prev`
    | `audio:broadcast:release`
    | `audio:broadcast:name:${string}`
    | `audio:broadcast:triplet:${string}.${string}.${string}`
    | `audio:plugin:${string}`
    | `audio:resolve:${string}`
    | `audio:resolve:user:${string}`
    | `audio:resolve:request:interaction:${string}`
    | `audio:resolve:request:interaction:${string}@${string}`
    | `url`
    | `back`
    | `background`
    | `background:${string}`
    | `background:none`
    | `background:default`
    | `background:resolve:${string}`
    | `background:resolve:user:${string}`
    | `background:resolve:request:interaction:${string}`
    | `background:resolve:request:interaction:${string}@${string}`
    | `url`
    | `busy:start:${string}`
    | `busy:start:loading`
    | `busy:stop:${string}`
    | `busy:stop:loading`
    | `cleanup`
    | `close`
    | `close`
    | `close:${string}`
    | `close:content_flag`
    | `content:${string}`
    | `content:data`
    | `content:request:interaction:${string}`
    | `content:request:interaction:custom_data_id`
    | `content:request:interaction:${string}@${string}`
    | `content:request:player:${string}`
    | `content:request:player:custom_data_id`
    | `content:user:${string}`
    | `data`
    | `delay:${string}:${string}:${string}`
    | `delay:custom_action_id:1:info:Delayed action executed (after 1 second).`
    | `delay:custom_action_id:2:info:Delayed action executed (after 2 seconds).`
    | `delay:custom_action_id:30:info:Delayed action executed (after 30 seconds).`
    | `delay:${string}:cancel`
    | `delay:custom_action_id:cancel`
    | `delay:${string}:execute`
    | `delay:custom_action_id:execute`
    | `delay:${string}:restart`
    | `delay:custom_action_id:restart`
    | `dialog:${string}`
    | `dialog:reload`
    | `dialog:restart`
    | `dialog:leave`
    | `dialog:exit`
    | `dialog:application`
    | `dialog:action_not_available`
    | `dialog:action_not_available_for_platform`
    | `dialog:video_not_available`
    | `dialog:audio_not_available`
    | `dialog:content_not_available`
    | `dialog:feature_not_available`
    | `dialog:none`
    | `none`
    | `enter:${string}`
    | `enter:1234`
    | `action`
    | `data`
    | `error:${string}`
    | `error:This is an error message.`
    | `event:${string}`
    | `event:custom_event_id`
    | `execute:${string}`
    | `execute:accurate:${string}`
    | `execute:code:${string}`
    | `execute:code:accurate:${string}`
    | `execute:code:request:interaction:${string}`
    | `execute:code:request:interaction:custom_data_id`
    | `execute:code:request:interaction:${string}@${string}`
    | `execute:code:request:player:${string}`
    | `execute:code:request:player:custom_data_id`
    | `execute:code:user:${string}`
    | `execute:code:user:accurate:${string}`
    | `execute:fetch:${string}`
    | `execute:fetch:accurate:${string}`
    | `execute:fetch:user:${string}`
    | `execute:fetch:user:accurate:${string}`
    | `execute:info:${string}`
    | `execute:info:accurate:${string}`
    | `execute:info:${string}`
    | `execute:info:request:interaction:${string}`
    | `execute:info:request:interaction:custom_data_id`
    | `execute:info:${string}`
    | `execute:info:request:interaction:${string}@${string}`
    | `execute:info:${string}`
    | `execute:info:request:player:${string}`
    | `execute:info:request:player:custom_data_id`
    | `execute:info:${string}`
    | `execute:info:user:${string}`
    | `execute:info:${string}`
    | `execute:info:user:accurate:${string}`
    | `execute:info:${string}`
    | `execute:request:interaction:${string}`
    | `execute:request:interaction:custom_data_id`
    | `execute:request:interaction:${string}@${string}`
    | `execute:request:player:${string}`
    | `execute:request:player:custom_data_id`
    | `execute:response:${string}`
    | `execute:response:user:${string}`
    | `execute:response:accurate:${string}`
    | `execute:response:user:accurate:${string}`
    | `execute:response:request:player:${string}`
    | `execute:response:request:interaction:${string}`
    | `execute:response:request:interaction:${string}@${string}`
    | `requestAction`
    | `requestData`
    | `execute:service:${string}`
    | `execute:service:accurate:${string}`
    | `execute:service:fetch:${string}`
    | `execute:service:fetch:accurate:${string}`
    | `execute:service:fetch:user:${string}`
    | `execute:service:fetch:user:accurate:${string}`
    | `execute:service:info:${string}`
    | `execute:info:${string}`
    | `execute:service:info:accurate:${string}`
    | `execute:info:${string}`
    | `execute:service:info:request:interaction:${string}`
    | `execute:service:info:request:interaction:custom_data_id`
    | `execute:info:${string}`
    | `execute:service:info:request:interaction:${string}@${string}`
    | `execute:info:${string}`
    | `execute:service:info:request:player:${string}`
    | `execute:service:info:request:player:custom_data_id`
    | `execute:info:${string}`
    | `execute:service:info:user:${string}`
    | `execute:info:${string}`
    | `execute:service:info:user:accurate:${string}`
    | `execute:info:${string}`
    | `execute:service:request:interaction:${string}`
    | `execute:service:request:interaction:custom_data_id`
    | `execute:service:request:interaction:${string}@${string}`
    | `execute:service:request:player:${string}`
    | `execute:service:request:player:custom_data_id`
    | `execute:service:response:${string}`
    | `execute:service:response:user:${string}`
    | `execute:service:response:accurate:${string}`
    | `execute:service:response:user:accurate:${string}`
    | `execute:service:response:request:player:${string}`
    | `execute:service:response:request:interaction:${string}`
    | `execute:service:response:request:interaction:${string}@${string}`
    | `requestAction`
    | `requestData`
    | `execute:service:slider:${string}`
    | `execute:service:slider:accurate:${string}`
    | `execute:service:slider:request:interaction:${string}`
    | `execute:service:slider:request:interaction:custom_data_id`
    | `execute:service:slider:request:interaction:${string}@${string}`
    | `execute:service:slider:request:player:${string}`
    | `execute:service:slider:request:player:custom_data_id`
    | `execute:service:slider:user:${string}`
    | `execute:service:slider:user:accurate:${string}`
    | `execute:service:user:${string}`
    | `execute:service:user:accurate:${string}`
    | `execute:service:video:${string}`
    | `execute:video:${string}`
    | `execute:service:video:accurate:${string}`
    | `execute:video:${string}`
    | `execute:service:video:request:interaction:${string}`
    | `execute:service:video:request:interaction:custom_data_id`
    | `execute:video:${string}`
    | `execute:service:video:request:interaction:${string}@${string}`
    | `execute:video:${string}`
    | `execute:service:video:request:player:${string}`
    | `execute:service:video:request:player:custom_data_id`
    | `execute:video:${string}`
    | `execute:service:video:user:${string}`
    | `execute:video:${string}`
    | `execute:service:video:user:accurate:${string}`
    | `execute:video:${string}`
    | `execute:slider:${string}`
    | `execute:slider:accurate:${string}`
    | `execute:slider:request:interaction:${string}`
    | `execute:slider:request:interaction:custom_data_id`
    | `execute:slider:request:interaction:${string}@${string}`
    | `execute:slider:request:player:${string}`
    | `execute:slider:request:player:custom_data_id`
    | `execute:slider:user:${string}`
    | `execute:slider:user:accurate:${string}`
    | `execute:user:${string}`
    | `execute:user:accurate:${string}`
    | `execute:video:${string}`
    | `execute:video:accurate:${string}`
    | `execute:video:${string}`
    | `execute:video:request:interaction:${string}`
    | `execute:video:request:interaction:custom_data_id`
    | `execute:video:${string}`
    | `execute:video:request:interaction:${string}@${string}`
    | `execute:video:${string}`
    | `execute:video:request:player:${string}`
    | `execute:video:request:player:custom_data_id`
    | `execute:video:${string}`
    | `execute:video:user:${string}`
    | `execute:video:${string}`
    | `execute:video:user:accurate:${string}`
    | `execute:video:${string}`
    | `exit`
    | `focus:${string}`
    | `focus:content_item_id`
    | `focus:control:${string}`
    | `focus:control:menu`
    | `focus:control:content`
    | `focus:index:${string}`
    | `focus:index:0`
    | `fullscreen`
    | `history:back`
    | `history:clear`
    | `history:start`
    | `history:validate`
    | `home`
    | `image:${string}`
    | `image:context`
    | `image:resolve:${string}`
    | `image:resolve:user:${string}`
    | `image:resolve:request:interaction:${string}`
    | `image:resolve:request:interaction:${string}@${string}`
    | `url`
    | `info:${string}`
    | `info:This is an info message.`
    | `interaction:busy:start:${string}`
    | `interaction:busy:start:loading`
    | `interaction:busy:stop:${string}`
    | `interaction:busy:stop:loading`
    | `interaction:commit`
    | `interaction:commit:code`
    | `interaction:commit:dictionary`
    | `interaction:commit:info`
    | `interaction:commit:info:${string}`
    | `interaction:commit:info:extended`
    | `interaction:commit:info:base`
    | `interaction:commit:info:application`
    | `interaction:commit:info:framework`
    | `interaction:commit:info:content`
    | `interaction:commit:info:dictionary`
    | `interaction:commit:info:screen`
    | `interaction:commit:info:time`
    | `interaction:commit:message:${string}`
    | `interaction:commit:message:This is an interaction message.`
    | `interaction:commit:response:${string}`
    | `interaction:commit:response:user:${string}`
    | `interaction:commit:response:accurate:${string}`
    | `interaction:commit:response:user:accurate:${string}`
    | `interaction:commit:response:request:player:${string}`
    | `interaction:commit:slider`
    | `interaction:commit:string:${string}:${string}`
    | `interaction:commit:string:transform:Media Station X`
    | `interaction:commit:string:normalize:EW6l] 801JCU; )`
    | `interaction:commit:video`
    | `interaction:commit:video:${string}`
    | `interaction:commit:video:info`
    | `interaction:commit:video:data`
    | `interaction:commit:video:resume`
    | `interaction:commit:video:volume`
    | `interaction:commit:video:scene`
    | `interaction:load:${string}`
    | `interaction:load:none`
    | `interaction:commit`
    | `interaction:reload`
    | `interaction:unload`
    | `invalidate:content`
    | `invalidate:content:${string}`
    | `invalidate:content:content_item_id`
    | `invalidate:content:flag:${string}`
    | `invalidate:content:flag:content_flag`
    | `invalidate:content:overlay:${string}`
    | `invalidate:content:overlay:content_item_id`
    | `invalidate:content:underlay:${string}`
    | `invalidate:content:underlay:content_item_id`
    | `invalidate:menu`
    | `invalidate:menu:flag:${string}`
    | `invalidate:menu:flag:content_flag`
    | `invalidate:menu:${string}`
    | `invalidate:menu:menu_item_id`
    | `invalidate:panel`
    | `invalidate:panel:flag:${string}`
    | `invalidate:panel:flag:content_flag`
    | `invalidate:panel:${string}`
    | `invalidate:panel:content_item_id`
    | `invalidate:panel:overlay:${string}`
    | `invalidate:panel:overlay:content_item_id`
    | `invalidate:panel:underlay:${string}`
    | `invalidate:panel:underlay:content_item_id`
    | `key:${string}`
    | `key:left`
    | `key:right`
    | `key:up`
    | `key:down`
    | `key:execute`
    | `key:back`
    | `key:red`
    | `key:green`
    | `key:yellow`
    | `key:blue`
    | `key:channel_up`
    | `key:channel_down`
    | `key:play`
    | `key:pause`
    | `key:stop`
    | `key:code:${string}`
    | `key:code:37`
    | `key:code:39`
    | `key:code:38`
    | `key:code:40`
    | `key:code:13`
    | `key:code:8`
    | `leave`
    | `link:${string}`
    | `link:replace:${string}`
    | `link:window:${string}`
    | `live`
    | `log`
    | `log:clear`
    | `logger:debug:${string}`
    | `logger:debug:This is a debug message.`
    | `logger:error:${string}`
    | `logger:error:This is an error message.`
    | `logger:info:${string}`
    | `logger:info:This is an info message.`
    | `logger:success:${string}`
    | `logger:success:This is a success message.`
    | `logger:warn:${string}`
    | `logger:warn:This is a warning message.`
    | `main`
    | `menu`
    | `menu:${string}`
    | `menu:data`
    | `menu:request:interaction:${string}`
    | `menu:request:interaction:custom_data_id`
    | `menu:request:interaction:${string}@${string}`
    | `menu:request:player:${string}`
    | `menu:request:player:custom_data_id`
    | `menu:user:${string}`
    | `notification:${string}`
    | `notification:This is a notification message.`
    | `options`
    | `panel:${string}`
    | `panel:data`
    | `panel:request:interaction:${string}`
    | `panel:request:interaction:custom_data_id`
    | `panel:request:interaction:${string}@${string}`
    | `panel:request:player:${string}`
    | `panel:request:player:custom_data_id`
    | `panel:user:${string}`
    | `playback`
    | `player`
    | `player:action`
    | `player:auto:${string}`
    | `player:auto:next`
    | `player:auto:prev`
    | `player:auto:play`
    | `player:auto:pause`
    | `player:auto:play_pause`
    | `player:auto:forward`
    | `player:auto:rewind`
    | `player:auto:restart`
    | `player:auto:goto:first`
    | `player:auto:goto:last`
    | `player:background:${string}`
    | `player:background:none`
    | `player:background:default`
    | `background`
    | `player:busy:start:${string}`
    | `player:busy:start:loading`
    | `player:busy:stop:${string}`
    | `player:busy:stop:loading`
    | `player:button:${string}:disable`
    | `player:button:content:disable`
    | `player:button:restart:disable`
    | `player:button:prev:disable`
    | `player:button:rewind:disable`
    | `player:button:play_pause:disable`
    | `player:button:forward:disable`
    | `player:button:next:disable`
    | `player:button:speed:disable`
    | `player:button:${string}:enable`
    | `player:button:content:enable`
    | `player:button:restart:enable`
    | `player:button:prev:enable`
    | `player:button:rewind:enable`
    | `player:button:play_pause:enable`
    | `player:button:forward:enable`
    | `player:button:next:enable`
    | `player:button:speed:enable`
    | `player:button:${string}:execute`
    | `player:button:content:execute`
    | `player:button:restart:execute`
    | `player:button:prev:execute`
    | `player:button:rewind:execute`
    | `player:button:play_pause:execute`
    | `player:button:forward:execute`
    | `player:button:next:execute`
    | `player:button:speed:execute`
    | `player:button:eject:execute`
    | `player:button:${string}:focus`
    | `player:button:content:focus`
    | `player:button:restart:focus`
    | `player:button:prev:focus`
    | `player:button:rewind:focus`
    | `player:button:play_pause:focus`
    | `player:button:forward:focus`
    | `player:button:next:focus`
    | `player:button:speed:focus`
    | `player:button:eject:focus`
    | `player:button:${string}:setup`
    | `player:button:content:setup`
    | `player:button:restart:setup`
    | `player:button:prev:setup`
    | `player:button:rewind:setup`
    | `player:button:play_pause:setup`
    | `player:button:forward:setup`
    | `player:button:next:setup`
    | `player:button:speed:setup`
    | `player:commit`
    | `player:commit:code`
    | `player:commit:dictionary`
    | `player:commit:info`
    | `player:commit:info:${string}`
    | `player:commit:info:extended`
    | `player:commit:info:base`
    | `player:commit:info:application`
    | `player:commit:info:framework`
    | `player:commit:info:content`
    | `player:commit:info:dictionary`
    | `player:commit:info:screen`
    | `player:commit:info:time`
    | `player:commit:message:${string}`
    | `player:commit:message:This is a player message.`
    | `player:commit:response:${string}`
    | `player:commit:response:user:${string}`
    | `player:commit:response:accurate:${string}`
    | `player:commit:response:user:accurate:${string}`
    | `player:commit:response:request:interaction:${string}`
    | `player:commit:response:request:interaction:${string}@${string}`
    | `player:commit:slider`
    | `player:commit:string:${string}:${string}`
    | `player:commit:string:transform:Media Station X`
    | `player:commit:string:normalize:EW6l] 801JCU; )`
    | `player:commit:video`
    | `player:commit:video:${string}`
    | `player:commit:video:info`
    | `player:commit:video:data`
    | `player:commit:video:resume`
    | `player:commit:video:volume`
    | `player:commit:video:scene`
    | `player:content`
    | `player:content:${string}`
    | `player:content:user:${string}`
    | `player:content:request:interaction:${string}`
    | `player:content:request:interaction:${string}@${string}`
    | `player:content:data`
    | `player:control:action:${string}`
    | `player:control:action:info:Custom player control action executed.`
    | `player:control:action:default`
    | `player:default`
    | `execute`
    | `player:eject`
    | `player:forward`
    | `player:goto:${string}`
    | `player:goto:content_item_id`
    | `player:goto:current`
    | `player:goto:first`
    | `player:goto:index:${string}`
    | `player:goto:index:0`
    | `player:goto:last`
    | `player:goto:next`
    | `player:goto:number:${string}`
    | `player:goto:number:1`
    | `player:goto:prev`
    | `player:goto:random`
    | `player:goto:swap`
    | `player:hide`
    | `player:hide_pause`
    | `player:hide_play`
    | `player:info:image:${string}`
    | `player:info:image:default`
    | `player:info:overlay:${string}`
    | `player:info:overlay:full`
    | `player:info:overlay:default`
    | `player:info:size:${string}`
    | `player:info:size:small`
    | `player:info:size:medium`
    | `player:info:size:large`
    | `player:info:size:extra-large`
    | `player:info:size:default`
    | `player:info:text:${string}`
    | `player:info:text:Additional video/audio information.`
    | `player:info:text:default`
    | `player:invalidate`
    | `player:label:content:${string}`
    | `player:label:content:Custom player content label`
    | `player:label:content:default`
    | `playerLabel`
    | `player:label:duration:${string}`
    | `player:label:duration:Custom player duration label`
    | `player:label:duration:Custom player duration label (${string})`
    | `player:label:duration:default`
    | `player:label:extension:${string}`
    | `player:label:extension:${string}`
    | `player:label:extension:default`
    | `player:label:position:${string}`
    | `player:label:position:Custom player position label`
    | `player:label:position:Custom player position label (${string})`
    | `player:label:position:default`
    | `player:label:speed:${string}`
    | `player:label:speed:Custom player speed label`
    | `player:label:speed:Custom player speed label (${string})`
    | `player:label:speed:default`
    | `player:menu:${string}`
    | `player:menu:user:${string}`
    | `player:menu:request:interaction:${string}`
    | `player:menu:request:interaction:${string}@${string}`
    | `player:menu:data`
    | `player:next`
    | `player:pause`
    | `player:play`
    | `player:play_pause`
    | `player:prev`
    | `player:progress:color:${string}`
    | `player:progress:color:msx-red`
    | `player:progress:color:default`
    | `player:progress:duration:${string}`
    | `player:progress:duration:60`
    | `player:progress:duration:-1`
    | `player:progress:marker:disable`
    | `player:progress:marker:enable`
    | `player:progress:marker:invalidate`
    | `player:progress:position:${string}`
    | `player:progress:position:0`
    | `player:progress:position:-1`
    | `player:progress:type:${string}`
    | `player:progress:type:position`
    | `player:progress:type:position:${string} ${string}`
    | `player:progress:type:number`
    | `player:progress:type:number:${string} ${string}`
    | `player:progress:type:percentage`
    | `player:progress:type:time:${string}`
    | `player:progress:type:text:${string}`
    | `player:progress:type:reverse:position`
    | `player:progress:type:reverse:position:${string} ${string}`
    | `player:progress:type:reverse:number`
    | `player:progress:type:reverse:number:${string} ${string}`
    | `player:progress:type:reverse:percentage`
    | `player:progress:type:reverse:time:${string}`
    | `player:progress:type:reverse:text:${string}`
    | `player:progress:type:difference:position`
    | `player:progress:type:difference:position:${string} ${string}`
    | `player:progress:type:difference:number`
    | `player:progress:type:difference:number:${string} ${string}`
    | `player:progress:type:difference:percentage`
    | `player:progress:type:difference:time:${string}`
    | `player:progress:type:difference:text:${string}`
    | `player:progress:type:fix:Fix progress label`
    | `player:progress:type:default`
    | `default`
    | `time:hh:mm:ss`
    | `position:`
    | `number:`
    | `player:refresh`
    | `player:reset`
    | `player:restart`
    | `player:rewind`
    | `player:seek:${string}`
    | `player:seek:10`
    | `player:seek:+10`
    | `player:seek:-10`
    | `player:seek:10%`
    | `player:seek:+10%`
    | `player:seek:-10%`
    | `player:show`
    | `player:show:${string}`
    | `player:show:left`
    | `player:show:right`
    | `player:show:up`
    | `player:show:down`
    | `player:show:execute`
    | `player:show:code:${string}`
    | `player:show:code:37`
    | `player:show:code:39`
    | `player:show:code:38`
    | `player:show:code:40`
    | `player:show:code:13`
    | `player:show_pause`
    | `player:show_pause:${string}`
    | `player:show_pause:left`
    | `player:show_pause:right`
    | `player:show_pause:up`
    | `player:show_pause:down`
    | `player:show_pause:execute`
    | `player:show_pause:code:${string}`
    | `player:show_pause:code:37`
    | `player:show_pause:code:39`
    | `player:show_pause:code:38`
    | `player:show_pause:code:40`
    | `player:show_pause:code:13`
    | `player:show_play`
    | `player:show_play:${string}`
    | `player:show_play:left`
    | `player:show_play:right`
    | `player:show_play:up`
    | `player:show_play:down`
    | `player:show_play:execute`
    | `player:show_play:code:${string}`
    | `player:show_play:code:37`
    | `player:show_play:code:39`
    | `player:show_play:code:38`
    | `player:show_play:code:40`
    | `player:show_play:code:13`
    | `player:speed`
    | `player:speed:dec`
    | `player:speed:inc`
    | `player:speed:set:${string}`
    | `player:speed:set:0.125`
    | `player:speed:set:0.25`
    | `player:speed:set:0.5`
    | `player:speed:set:1`
    | `player:speed:set:2`
    | `player:speed:set:4`
    | `player:speed:set:8`
    | `player:stop`
    | `player:sync`
    | `player:ticking:restart`
    | `0t`
    | `player:video:clear`
    | `player:video:duration:${string}`
    | `player:video:duration:60`
    | `-1`
    | `player:video:position:${string}`
    | `player:video:position:0`
    | `custom:video:seek`
    | `-1`
    | `-2`
    | `player:video:speed:${string}`
    | `player:video:speed:1`
    | `player:video:state:${string}`
    | `player:video:state:2`
    | `playlist:${string}`
    | `playlist:auto:${string}`
    | `playlist:auto:data`
    | `playlist:auto:request:interaction:${string}`
    | `playlist:auto:request:interaction:custom_data_id`
    | `playlist:auto:request:interaction:${string}@${string}`
    | `playlist:auto:request:player:${string}`
    | `playlist:auto:request:player:custom_data_id`
    | `playlist:auto:user:${string}`
    | `playlist:data`
    | `playlist:request:interaction:${string}`
    | `playlist:request:interaction:custom_data_id`
    | `playlist:request:interaction:${string}@${string}`
    | `playlist:request:player:${string}`
    | `playlist:request:player:custom_data_id`
    | `playlist:user:${string}`
    | `quiet`
    | `release:content`
    | `release:menu`
    | `release:panel`
    | `reload`
    | `reload:content`
    | `reload:menu`
    | `reload:panel`
    | `reopen:${string}`
    | `reopen:key1=value1&amp;key2=value2`
    | `replace:content:${string}:${string}`
    | `replace:content:content_flag:user:${string}`
    | `replace:content:content_flag:request:interaction:${string}`
    | `replace:content:content_flag:request:interaction:${string}@${string}`
    | `replace:menu:${string}:${string}`
    | `replace:menu:content_flag:user:${string}`
    | `replace:menu:content_flag:request:interaction:${string}`
    | `replace:menu:content_flag:request:interaction:${string}@${string}`
    | `replace:panel:${string}:${string}`
    | `replace:panel:content_flag:user:${string}`
    | `replace:panel:content_flag:request:interaction:${string}`
    | `replace:panel:content_flag:request:interaction:${string}@${string}`
    | `response:${string}`
    | `response:rq10_1541593729708`
    | `restart`
    | `resume:cancel`
    | `resume:clear`
    | `resume:clear:${string}`
    | `resume:clear:content_item_id`
    | `resume:clear:custom_resume_key`
    | `resume:clear:current`
    | `resume:clear:hash:${string}`
    | `resume:clear:hash:511673863`
    | `resume:position:${string}`
    | `resume:position:10`
    | `resume:position:10%`
    | `resume:position:none`
    | `none`
    | `video:${string}`
    | `audio:${string}`
    | `playlist:${string}`
    | `selection`
    | `settings`
    | `settings:about`
    | `settings:animate`
    | `settings:animate:${string}`
    | `settings:animate:0`
    | `settings:animate:1`
    | `settings:animate:2`
    | `settings:hover_effect`
    | `settings:hover_effect:${string}`
    | `settings:hover_effect:0`
    | `settings:hover_effect:1`
    | `settings:hover_effect:2`
    | `settings:immersive_mode`
    | `settings:immersive_mode:${string}`
    | `settings:immersive_mode:0`
    | `settings:immersive_mode:1`
    | `settings:input`
    | `settings:input:${string}`
    | `settings:input:0`
    | `settings:input:1`
    | `settings:input:2`
    | `settings:input:3`
    | `settings:layout`
    | `settings:layout:${string}`
    | `settings:layout:0.5`
    | `settings:layout:0.75`
    | `settings:layout:1`
    | `settings:layout:1.5`
    | `settings:layout:3`
    | `settings:menu_button`
    | `settings:random_playback`
    | `settings:random_playback:${string}`
    | `settings:random_playback:0`
    | `settings:random_playback:1`
    | `settings:remote`
    | `settings:remote:${string}`
    | `settings:remote:0`
    | `settings:remote:1`
    | `settings:remote:2`
    | `settings:remote:3`
    | `settings:remote:4`
    | `settings:scale`
    | `settings:scale:${string}`
    | `settings:scale:default`
    | `settings:scale:auto`
    | `settings:scale:device`
    | `settings:scale:0.75`
    | `settings:scale:fix:0.75`
    | `settings:slideshow_interval`
    | `settings:slideshow_interval:${string}`
    | `settings:slideshow_interval:1000`
    | `settings:slideshow_interval:5000`
    | `settings:slideshow_interval:10000`
    | `settings:slideshow_interval:20000`
    | `settings:slideshow_interval:40000`
    | `settings:start`
    | `settings:transform`
    | `settings:transform:${string}`
    | `settings:transform:0`
    | `settings:transform:1`
    | `settings:transform:2`
    | `settings:validate_links`
    | `settings:validate_links:${string}`
    | `settings:validate_links:0`
    | `settings:validate_links:1`
    | `settings:zoom`
    | `settings:zoom:${string}`
    | `settings:zoom:default`
    | `settings:zoom:auto`
    | `settings:zoom:0.75`
    | `slider:action:${string}`
    | `slider:action:info:Custom image action executed.`
    | `slider:action:default`
    | `slider:break`
    | `slider:color:${string}`
    | `slider:color:msx-blue`
    | `slider:color:default`
    | `imageColor`
    | `slider:continue`
    | `slider:default`
    | `slider:eject`
    | `slider:execute:${string}`
    | `slider:execute:info:Slideshow action executed.`
    | `slider:extension:${string}`
    | `slider:extension:Custom image extension label`
    | `slider:extension:default`
    | `slider:goto:${string}`
    | `slider:goto:content_item_id`
    | `slider:goto:first`
    | `slider:goto:index:${string}`
    | `slider:goto:index:0`
    | `slider:goto:last`
    | `slider:goto:next`
    | `slider:goto:number:${string}`
    | `slider:goto:number:1`
    | `slider:goto:prev`
    | `slider:icon:${string}`
    | `slider:icon:info`
    | `slider:icon:default`
    | `slider:label:${string}`
    | `slider:label:Custom image label`
    | `slider:label:default`
    | `slider:labels:hide`
    | `slider:labels:play_pause`
    | `slider:labels:show`
    | `slider:labels:toggle`
    | `slider:next`
    | `slider:options`
    | `slider:options:execute`
    | `slider:options:select:${string}`
    | `slider:options:select:slideshow`
    | `slider:options:select:right_rotation`
    | `slider:options:select:left_rotation`
    | `slider:options:select:full_rotation`
    | `slider:options:select:reset_rotation`
    | `slider:pause`
    | `slider:play`
    | `slider:play_pause`
    | `slider:prev`
    | `slider:reset`
    | `slider:restart`
    | `slider:rotate:${string}`
    | `slider:rotate:right`
    | `slider:rotate:left`
    | `slider:rotate:full`
    | `slider:rotate:full-right`
    | `slider:rotate:full-left`
    | `slider:rotate:reset`
    | `slider:rotate:-270`
    | `slider:rotate:-180`
    | `slider:rotate:-90`
    | `slider:rotate:0`
    | `slider:rotate:90`
    | `slider:rotate:180`
    | `slider:rotate:270`
    | `slider:stop`
    | `slider:sync`
    | `slideshow:${string}`
    | `slideshow:data`
    | `slideshow:request:interaction:${string}`
    | `slideshow:request:interaction:custom_data_id`
    | `slideshow:request:interaction:${string}@${string}`
    | `slideshow:request:player:${string}`
    | `slideshow:request:player:custom_data_id`
    | `slideshow:user:${string}`
    | `start`
    | `still`
    | `success:${string}`
    | `success:This is a success message.`
    | `system:hbbtv:${string}`
    | `system:hbbtv:show`
    | `system:hbbtv:hide`
    | `system:hbbtv:launch:${string}`
    | `system:hbbtv:foreground`
    | `system:hbbtv:background`
    | `system:hbbtv:transient`
    | `system:hbbtv:update`
    | `system:lg:${string}`
    | `system:lg:launch:${string}`
    | `system:netcast:${string}`
    | `system:netcast:menu`
    | `system:netcast:ratio`
    | `system:options`
    | `system:samsung:${string}`
    | `system:samsung:launch:${string}`
    | `system:tizen:${string}`
    | `system:tizen:launch`
    | `system:tizen:launch:${string}`
    | `system:tizen:keys:mapped`
    | `system:tizen:keys:unmapped`
    | `system:tvx:${string}`
    | `system:tvx:about`
    | `system:tvx:settings`
    | `system:tvx:restart`
    | `system:tvx:exit`
    | `system:tvx:log`
    | `system:tvx:log:clear`
    | `system:tvx:system_log`
    | `system:tvx:system_log:clear`
    | `system:tvx:options`
    | `system:tvx:launch`
    | `system:tvx:launch:${string}`
    | `system:uwp:${string}`
    | `system:uwp:launch:${string}`
    | `test`
    | `time:clear`
    | `time:init`
    | `time`
    | `timeZone`
    | `time:set`
    | `offset`
    | `zoneOffset`
    | `trigger:${string}:${string}`
    | `trigger:load:info:Video loaded.`
    | `trigger:ready:info:Video ready.`
    | `trigger:start:info:Video started.`
    | `trigger:ending:info:Video is ending (video is playing and 10 seconds or less are remaining).`
    | `trigger:end:info:Video ended.`
    | `trigger:complete:info:Video completed.`
    | `trigger:10:info:10 seconds of video passed.`
    | `trigger:10%:info:10% of video passed.`
    | `trigger:10t:info:10 ticks of video passed.`
    | `trigger:-10:info:Last 10 seconds of video passed.`
    | `trigger:20:shot:info:20 seconds of video passed (shot).`
    | `trigger:20%:shot:info:20% of video passed (shot).`
    | `trigger:20t:shot:info:20 ticks of video passed (shot).`
    | `trigger:-20:shot:info:Last 20 seconds of video passed (shot).`
    | `trigger:quartile1:info:First quartile of video entered.`
    | `trigger:quartile2:info:Second quartile of video entered.`
    | `trigger:quartile3:info:Third quartile of video entered.`
    | `trigger:quartile4:info:Fourth quartile of video entered.`
    | `trigger:first_quartile:info:First quartile of video reached.`
    | `trigger:midpoint:info:Midpoint of video reached.`
    | `trigger:third_quartile:info:Third quartile of video reached.`
    | `trigger:play:info:Video is playing.`
    | `trigger:pause:info:Video paused.`
    | `trigger:stop:info:Video stopped.`
    | `trigger:active:info:Video player is visible or video moved to foreground.`
    | `trigger:inactive:info:Video moved to background.`
    | `trigger:player:info:Video player is visible.`
    | `trigger:foreground:info:Video moved to foreground.`
    | `trigger:background:info:Video moved to background.`
    | `trigger:back:info:Video back executed.`
    | `trigger:back:none`
    | `update:content:${string}`
    | `update:content:content_item_id`
    | `update:content:overlay:${string}`
    | `update:content:overlay:content_item_id`
    | `update:content:underlay:${string}`
    | `update:content:underlay:content_item_id`
    | `update:menu:${string}`
    | `update:menu:menu_item_id`
    | `update:panel:${string}`
    | `update:panel:content_item_id`
    | `update:panel:overlay:${string}`
    | `update:panel:overlay:content_item_id`
    | `update:panel:underlay:${string}`
    | `update:panel:underlay:content_item_id`
    | `video:${string}`
    | `video:auto:${string}`
    | `video:auto:broadcast:${string}`
    | `video:auto:broadcast:current`
    | `video:auto:broadcast:next`
    | `video:auto:broadcast:prev`
    | `video:auto:broadcast:release`
    | `video:auto:broadcast:name:${string}`
    | `video:auto:broadcast:triplet:${string}.${string}.${string}`
    | `video:auto:plugin:${string}`
    | `video:auto:resolve:${string}`
    | `video:auto:resolve:user:${string}`
    | `video:auto:resolve:request:interaction:${string}`
    | `video:auto:resolve:request:interaction:${string}@${string}`
    | `url`
    | `video:broadcast:${string}`
    | `video:broadcast:current`
    | `video:broadcast:next`
    | `video:broadcast:prev`
    | `video:broadcast:release`
    | `video:broadcast:name:${string}`
    | `video:broadcast:triplet:${string}.${string}.${string}`
    | `video:plugin:${string}`
    | `video:resolve:${string}`
    | `video:resolve:user:${string}`
    | `video:resolve:request:interaction:${string}`
    | `video:resolve:request:interaction:${string}@${string}`
    | `url`
    | `volume`
    | `volume:action`
    | `volume:dec`
    | `volume:hide`
    | `volume:inc`
    | `volume:mute`
    | `volume:set:${string}`
    | `volume:set:100`
    | `volume:set:50`
    | `volume:set:0`
    | `volume:show`
    | `volume:toggle_show`
    | `volume:unmute`
    | `volume:toggle`
    | `warn:${string}`
    | `warn:This is a warning message.`
    | `[${string}]`
