// import { Image } from "../sharedObjects/image.ts-tbd"
// import { ContentItem } from "./contentObjects"

// export const poster = (title: string, year: Date, description: string | null = null, poster: Image, action: string) : ContentItem => new ContentItem({
//     id: `${title.replace(/\/).toLowerCase()}_poster`,
//     type: "separate",
//     key: "",
//     layout: null,
//     area : null,
//     offset : null,
//     display : true,
//     enable: true,
//     focus: false,
//     execute: false,
//     enumerate: true,
//     compress: false,
//     shortcut: false,
//     group: "",
//     color: "",
//     title: "",
//     titleHeader: title,
//     titleFooter: year.getFullYear().toString(),
//     label: "",
//     icon: "blank",
//     iconSize: "medium",
//     headline: "",
//     text: "",
//     tag: "",
//     tagColor: "",
//     badge: "",
//     badgeColor: "",
//     stamp: "",
//     stampColor: "",
//     progress: -1,
//     progressColor: "",
//     wrapperColor: "",
//     image: poster.getDefaultQuality(),
//     imageFiller: "smart",
//     imageWidth: -1,
//     imageHeight: -1,
//     imageOverlay: -1,
//     imagePreload: false,
//     imageLabel: "",
//     imageColor: "",
//     imageScreenFiller: "",
//     imageBoundary: false,
//     playerLabel: "",
//     background: null,
//     extensionIcon: "blank",
//     extensionLabel: "",
//     action: action,
//     data: null,
//     properties: null,
//     live: null,
//     selection: description,
//     options: null
// })
